<?php if(!defined('KIRBY')) exit ?>

title: Page
pages:
  template:
    - _submenu
    - _hero
    - _section
files: true
fields:
  title:
    label: Title
    type:  text
  info:
    type: info
    text: "<strong>This is a primary page.</strong> <br/> The content of a primary page is generated by adding sub-pages."